### ISSUE TITLE
I have a problem with argument setInputFiles(input, [file]).

### ISSUE THREAD

**Issue by anankuntakamdev** [fisker/set-input-files#1387]
I get an error  Uncaught TypeError: Failed to execute 'add' on 'DataTransferItemList': parameter 1 is not of type 'File'.

**Comment by anankuntakamdev** [comment]
$('#test').on('click', function(e) {
            let element = $("#problemImage");
            let elm = element[0];
            console.log(elm); // = <input type="file" class="custom-file-input" id="problemImage" name="problemImage[]" value="" accept="image/*" multiple="">
            let imgArray = new Array();

            imgArray[0] = new Image();
            imgArray[0].src = 'img/problem/1.jpg';
            console.log(imgArray[0]); // = <img src="img/problem/1.jpg">

            setInputFiles(elm, [imgArray[0]]);
        });

**Comment by anankuntakamdev** [comment]
` $('#test').on('click', function(e) {
            let element = $("#problemImage");
            let elm = element[0];
            console.log(elm); // = <input type="file" class="custom-file-input" id="problemImage" name="problemImage[]" value="" accept="image/*" multiple="">
            let imgArray = new Array();

            imgArray[0] = new Image();
            imgArray[0].src = 'img/problem/1.jpg';
            console.log(imgArray[0]); // = <img src="img/problem/1.jpg">

            setInputFiles(elm, [imgArray[0]]);
        });`

**Comment by fisker** [comment]
Looks like you are really new to web, but I'm not a teacher, please try to search for docs on site like [`MDN`](https://developer.mozilla.org/en-US/docs/Web/API/File/File).

```html
    <script type="module">
        import setInputFiles from 'https://unpkg.com/set-input-files?module';

        $('#test').on('click', async function(e) {
            let element = $("#problemImage");
            let elm = element[0];

			const response = await fetch('img/problem/1.jpg')
			const blob = await response.blob();
			const file = new File([blob], '1.jpg');
            setInputFiles(elm, [file ]);
        });
    </script>
```
